# Generated by Django 2.2.16 on 2022-04-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220403_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=25, verbose_name='Confirmation code'),
        ),
    ]
