# Generated by Django 2.2.16 on 2022-04-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220403_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=100, verbose_name='Confirmation code'),
        ),
    ]
