# Generated by Django 2.2.16 on 2022-04-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220402_2018'),
        ('reviews', '0002_auto_20220403_1344'),
    ]

    operations = [
    ]
