# Generated by Django 2.2.16 on 2022-04-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_merge_20220403_1315'),
        ('reviews', '0004_auto_20220403_1206'),
    ]

    operations = [
    ]
