# Generated by Django 2.2.16 on 2022-04-07 19:52

import django.core.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220406_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2022, validators=[django.core.validators.MinValueValidator(1985), reviews.models.max_value_current_year], verbose_name='Год релиза'),
        ),
    ]
